import random

anime_shows = [
    "Attack on Titan",
    "Naruto",
    "Naruto: Shippuden",
    "Bleach",
    "One Piece",
    "Fullmetal Alchemist: Brotherhood",
    "Death Note",
    "Demon Slayer: Kimetsu no Yaiba",
    "Jujutsu Kaisen",
    "My Hero Academia",
    "Hunter x Hunter",
    "Tokyo Ghoul",
    "Black Clover",
    "Sword Art Online",
    "Chainsaw Man",
    "Spy x Family",
    "Re:Zero − Starting Life in Another World",
    "Steins;Gate",
    "Code Geass",
    "Vinland Saga",
    "Mob Psycho 100",
    "The Rising of the Shield Hero",
    "Fate/Zero",
    "Fate/Stay Night: Unlimited Blade Works",
    "Erased",
    "Your Lie in April",
    "The Promised Neverland",
    "Dr. Stone",
    "That Time I Got Reincarnated as a Slime",
    "No Game No Life",
    "Overlord",
    "Parasyte: The Maxim",
    "Toradora!",
    "Kaguya-sama: Love is War",
    "Clannad: After Story",
    "Haikyuu!!",
    "Dorohedoro",
    "Berserk",
    "Cowboy Bebop",
    "Samurai Champloo",
    "Trigun",
    "Neon Genesis Evangelion",
    "Made in Abyss",
    "Hellsing Ultimate",
    "Blue Exorcist",
    "Soul Eater",
    "Fairy Tail",
    "Fire Force",
    "Gurren Lagann",
    "Akame ga Kill!",
    "The Seven Deadly Sins",
    "Assassination Classroom",
    "Angel Beats!",
    "Noragami",
    "Bungo Stray Dogs",
    "Attack on Titan: Junior High",
    "To Your Eternity",
    "Oshi no Ko",
    "Mushoku Tensei: Jobless Reincarnation",
    "Zom 100: Bucket List of the Dead",
    "The Ancient Magus’ Bride",
    "Yuri!!! on Ice",
    "March Comes in Like a Lion",
    "Beastars",
    "Great Teacher Onizuka",
    "Black Lagoon",
    "Kill la Kill",
    "Psycho-Pass",
    "Ergo Proxy",
    "The Devil is a Part-Timer!",
    "Barakamon",
    "Nichijou",
    "One Punch Man",
    "The Disastrous Life of Saiki K.",
    "Konosuba: God’s Blessing on This Wonderful World!",
    "The Quintessential Quintuplets",
    "Rent-A-Girlfriend",
    "Horimiya",
    "Your Name",
    "Weathering With You",
    "Spirited Away",
    "Princess Mononoke",
    "Howl’s Moving Castle",
    "Nausicaä of the Valley of the Wind",
    "The Wind Rises",
    "Paprika",
    "Perfect Blue",
    "Summer Wars",
    "Wolf Children",
    "Belle",
    "A Silent Voice",
    "The Garden of Words"
]

def random_anime() -> str:
    return random.choice(anime_shows)